### ISSUE TITLE
Tasks not chaining properly

### ISSUE THREAD

**Issue by krusek** [BoltsFramework/Bolts-iOS#116] opened 2015-08-08 04:18 UTC
I have a `BFTask` that is returning false to `[ob isKindOfClass:[BFTask class]]` and yet returns `@"BFTask"` for `NSStringFromClass([obj class])`.

Here is a sample project: `git@github.com:krusek/Bolts-error.git`

**Comment by krusek** [comment] 2015-08-08 19:28
https://github.com/krusek/Bolts-error

**Comment by nlutsenko** [comment] 2015-08-08 19:54
Closing this one as a duplicate of #111
Let's continue discussion there.

**Closed by nlutsenko** 2015-08-08 19:54 UTC
