### ISSUE TITLE
Generic BFTasks for Swift?

### ISSUE THREAD

**Issue by scottrhoyt** [BoltsFramework/Bolts-iOS#196] opened 2015-11-04 06:46 UTC
I noticed that v1.2.2 added support for ObjC generics for `BFTask` and `BFTaskCompletionSource`. Are there any plans to support Swift generics as well? I imagine this could help cut down on a lot of type checking boilerplate.

**Comment by richardjrossiii** [comment] 2015-11-04 19:28
Duplicate of #61. But yes, it is coming!

**Closed by richardjrossiii** 2015-11-04 19:28 UTC
Labels: duplicate

**Comment by scottrhoyt** [comment] 2015-11-05 00:48
Thanks!
